#!/bin/sh

dl_subdir=7u7-b10
rpm=jdk-7u7-linux-x64.rpm
jdk=jdk1.7.0_07
jdk_pkg=jdk-1.7.0_07

check() {
        local name=$1
	local path=$2

	alternatives --display $name | grep -Fq "link currently points to $path"
	return $?
}

alternative() {
	local link=$1
	local name=$2
	local path=$3
	local priority=$4


	if ! check $name $path; then
		alternatives --install $link $name $path $priority
		alternatives --set $name $path
	fi
}

if [ "$1" = "check" ]; then
	if check java /usr/java/$jdk/jre/bin/java; then
		exit 0
	else
		exit 1
	fi
fi

if ! rpm -qa | grep -q ^$jdk_pkg; then
	cd /tmp
	wget --no-cookies --header "Cookie: gpw_e24=http://starjuice.net/;" \
		http://download.oracle.com/otn-pub/java/jdk/$dl_subdir/$rpm
	rpm -i $rpm
	rm $rpm
fi

alternative /usr/bin/java java /usr/java/$jdk/jre/bin/java 20000
alternative /usr/lib64/mozilla/plugins/libjavaplugin.so libjavaplugin.so.x86_64 \
	/usr/java/$jdk/jre/lib/amd64/libnpjp2.so 20000
alternative /usr/bin/javaws javaws /usr/java/$jdk/bin/javaws 20000
alternative /usr/bin/javac javac /usr/java/$jdk/bin/javac 20000
alternative /usr/bin/jar jar /usr/java/$jdk/bin/jar 20000
