#!/usr/bin/env ruby

manifest = ARGV.pop
Dir.chdir File.join(File.dirname(__FILE__), '..')
puppet = %w[ /usr/local/bin/puppet /usr/bin/puppet ].detect { |p| File.executable?(p) } || 'puppet'
system "sudo #{puppet} apply --modulepath modules --verbose #{ARGV.join(' ')} #{manifest}"
